// secretValidation.js - Shared validation helpers for JWT secret safety checks.

// GENERATED_SECRET_LENGTH is the exact length of crypto.randomBytes(64).toString('hex').
export const GENERATED_SECRET_LENGTH = 128;

// MINIMUM_SECRET_LENGTH is the shortest value this utility accepts for a JWT secret.
export const MINIMUM_SECRET_LENGTH = 32;

// HEX_SECRET_PATTERN accepts only lowercase or uppercase hexadecimal characters.
const HEX_SECRET_PATTERN = /^[a-f0-9]+$/i;

// validateSecret returns a structured result instead of throwing, so scripts can print friendly output.
export function validateSecret(secret) {
  const problems = [];
  const warnings = [];

  if (typeof secret !== 'string') {
    problems.push('JWT_SECRET must be a string.');
    return {
      valid: false,
      recommendedFormat: false,
      problems,
      warnings,
    };
  }

  const trimmedSecret = secret.trim();

  if (!trimmedSecret) {
    problems.push('JWT_SECRET is empty.');
  }

  if (trimmedSecret.length < MINIMUM_SECRET_LENGTH) {
    problems.push(`JWT_SECRET must be at least ${MINIMUM_SECRET_LENGTH} characters long.`);
  }

  const isHex = HEX_SECRET_PATTERN.test(trimmedSecret);
  const hasGeneratedLength = trimmedSecret.length === GENERATED_SECRET_LENGTH;

  if (!isHex) {
    problems.push('JWT_SECRET should contain only hexadecimal characters when generated by this tool.');
  }

  if (isHex && !hasGeneratedLength) {
    warnings.push(`JWT_SECRET should be exactly ${GENERATED_SECRET_LENGTH} hex characters when generated by this tool.`);
  }

  return {
    valid: problems.length === 0,
    recommendedFormat: isHex && hasGeneratedLength,
    problems,
    warnings,
  };
}
